[package]
name = "discord-image-bot"
version = "0.1.6"
authors = ["Cody Paschich <personal.voidlurker.net>"]

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
branch = "v0.5.0"

[dependencies.lazy_static]
version = "1.0.0"
